version: '3.8'

services:
  frontend:
    build: .
    container_name: smash-order-frontend-container
    ports:
      - "8080:80"
    networks:
      - smash-order-net

  backend:
    build:
      context: ../backend-restaurante-smash_order
    container_name: smash-order-backend-container
    ports:
      - "8081:8081"
    networks:
      - smash-order-net

networks:
  smash-order-net:
    driver: bridge
